### ISSUE TITLE
Soundcloud SDK

### ISSUE THREAD

**Issue by eliasmalik** [fourloops/CloudSound#26]
This is a question more than an issue:

Does the use of an API SDK contravene the "no frameworks/libraries" rule?

**Comment by franzmoro** [comment]
Streaming wouldn't have been possible otherwise (the player must be defined by their api framework). We did get to fetch the data through our own request at a certain point though (we refactored everything to play it safe though). We probably could get back to make it work that way, but it would take time

**Comment by otajor** [comment]
Google maps also comes with its own SDK/library without which you can't set up a google map.

We cleared it all with @RachBLondon and she said it was ok.

**Comment by eliasmalik** [comment]
cool
